name: ff
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.17.1 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  auto_size_text: 3.0.0
  flutter_svg: ^1.0.3
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/ff/assets/images/image11.png
    - packages/ff/assets/images/image13.png
    - packages/ff/assets/images/ellipse3.png
    - packages/ff/assets/images/image15.png
    - packages/ff/assets/images/ellipse2.png
    - packages/ff/assets/images/rectangle43.svg
    - packages/ff/assets/images/line1.svg
    - packages/ff/assets/images/line2.svg
    - packages/ff/assets/images/line5.svg
    - packages/ff/assets/images/line3.svg
    - packages/ff/assets/images/line4.svg
    - packages/ff/assets/images/line6.svg
    - packages/ff/assets/images/rectangle44.svg
    - packages/ff/assets/images/line7.svg
    - packages/ff/assets/images/line8.svg
    - packages/ff/assets/images/line9.svg
    - packages/ff/assets/images/line10.svg
    - packages/ff/assets/images/line11.svg
    - packages/ff/assets/images/line12.svg
    - packages/ff/assets/images/mas11.png
    - packages/ff/assets/images/mas12.png
    - packages/ff/assets/images/image14.png
    - packages/ff/assets/images/rectangle45.svg
    - packages/ff/assets/images/line13.svg
    - packages/ff/assets/images/line14.svg
    - packages/ff/assets/images/line15.svg
    - packages/ff/assets/images/line16.svg
    - packages/ff/assets/images/line17.svg
    - packages/ff/assets/images/line18.svg
    - packages/ff/assets/images/rectangle46.svg
    - packages/ff/assets/images/line19.svg
    - packages/ff/assets/images/line20.svg
    - packages/ff/assets/images/line21.svg
    - packages/ff/assets/images/line22.svg
    - packages/ff/assets/images/line23.svg
    - packages/ff/assets/images/line24.svg
    - packages/ff/assets/images/rectangle47.svg
    - packages/ff/assets/images/line25.svg
    - packages/ff/assets/images/line26.svg
    - packages/ff/assets/images/line27.svg
    - packages/ff/assets/images/line28.svg
    - packages/ff/assets/images/line29.svg
    - packages/ff/assets/images/line30.svg
    - packages/ff/assets/images/tarjetadecredito11.png
    - packages/ff/assets/images/paypal11.png
    - packages/ff/assets/images/casa32.png
    - packages/ff/assets/images/image2.png
    - packages/ff/assets/images/senalalt22.png
    - packages/ff/assets/images/computadoraportatil2.png
    - packages/ff/assets/images/image3.png
    - packages/ff/assets/images/busqueda12.png
    - packages/ff/assets/images/rectangle14.svg
    - packages/ff/assets/images/usuario2.png
    - packages/ff/assets/images/rectangle17.svg
    - packages/ff/assets/images/usuario3.png
    - packages/ff/assets/images/rectangle18.svg
    - packages/ff/assets/images/usuario4.png
    - packages/ff/assets/images/rectangle19.svg
    - packages/ff/assets/images/image16.png
    - packages/ff/assets/images/rectangle20.svg
    - packages/ff/assets/images/basura11.png
    - packages/ff/assets/images/basura12.png
    - packages/ff/assets/images/busqueda11.png
    - packages/ff/assets/images/image1.png
    - packages/ff/assets/images/senalalt21.png
    - packages/ff/assets/images/computadoraportatil1.png
    - packages/ff/assets/images/image4.png
    - packages/ff/assets/images/image5.png
    - packages/ff/assets/images/image6.png
    - packages/ff/assets/images/image7.png
    - packages/ff/assets/images/casa33.png
    - packages/ff/assets/images/image8.png
    - packages/ff/assets/images/image12.png
    - packages/ff/assets/images/image9.png
    - packages/ff/assets/images/image10.png
    - packages/ff/assets/images/ellipse1.png
    - packages/ff/assets/images/rectangle52.svg
    - packages/ff/assets/images/rectangle55.svg
    - packages/ff/assets/images/instagram1.png
    - packages/ff/assets/images/rectangle12.svg
    - packages/ff/assets/images/angulopequenohaciaabajo11.png
    - packages/ff/assets/images/rectangle58.svg
    - packages/ff/assets/images/rectangle59.svg
    - packages/ff/assets/images/rectangle60.svg
    - packages/ff/assets/images/rectangle61.svg
    - packages/ff/assets/images/rectangle63.svg
    - packages/ff/assets/images/rectangle65.svg
    - packages/ff/assets/images/rectangle66.svg
    - packages/ff/assets/images/rectangle69.svg
    - packages/ff/assets/images/rectangle70.svg
    - packages/ff/assets/images/rectangle68.svg
    - packages/ff/assets/images/angulopequenohaciaabajo12.png
    - packages/ff/assets/images/angulopequenohaciaabajo14.png
    - packages/ff/assets/images/angulopequenohaciaabajo15.png
    - packages/ff/assets/images/rectangle71.svg
    - packages/ff/assets/images/rectangle72.svg
    - packages/ff/assets/images/angulopequenohaciaabajo17.png
    - packages/ff/assets/images/angulopequenohaciaabajo16.png
    - packages/ff/assets/images/angulopequenohaciaabajo13.png
    - packages/ff/assets/images/casodecarta1.png
    - packages/ff/assets/images/rectangle5.svg
    - packages/ff/assets/images/rectangle6.svg
    - packages/ff/assets/images/rectangle7.svg
    - packages/ff/assets/images/rectangle8.svg
    - packages/ff/assets/images/rectangle9.svg
    - packages/ff/assets/images/rectangle3.svg
    - packages/ff/assets/images/rectangle4.svg
    - packages/ff/assets/images/usuario1.png
    - packages/ff/assets/images/casa31.png
    - packages/ff/assets/images/rectangle54.svg
    - packages/ff/assets/images/rectangle73.svg
    - packages/ff/assets/images/rectangle74.svg
    - packages/ff/assets/images/rectangle75.svg
    - packages/ff/assets/images/rectangle76.svg
    - packages/ff/assets/images/rectangle77.svg
    - packages/ff/assets/images/rectangle78.svg
    - packages/ff/assets/images/angulopequenohaciaabajo18.png
    - packages/ff/assets/images/rectangle79.svg
    - packages/ff/assets/images/rectangle80.svg
    - packages/ff/assets/images/rectangle81.svg
    - packages/ff/assets/images/rectangle82.svg
    - packages/ff/assets/images/angulopequenohaciaabajo19.png
    - packages/ff/assets/images/rectangle83.svg
    - packages/ff/assets/images/rectangle84.svg
    - packages/ff/assets/images/rectangle85.svg
    - packages/ff/assets/images/rectangle86.svg
    - packages/ff/assets/images/angulopequenohaciaabajo110.png
    - packages/ff/assets/images/rectangle50.svg
    - packages/ff/assets/images/rectangle51.svg
    - packages/ff/assets/images/v1024copia1.png
